export const APP_NAME = 'OLYMPEA Warrior'

export const NAV_ITEMS = {
  admin: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: 'LayoutDashboard' },
    { label: 'Usuarios', path: '/admin/usuarios', icon: 'Users' },
    { label: 'Coaches', path: '/admin/coaches', icon: 'UserCog' },
    { label: 'Alunos', path: '/admin/alunos', icon: 'GraduationCap' },
    { label: 'Programacao', path: '/admin/programacao', icon: 'CalendarDays' },
    { label: 'Fases', path: '/admin/fases', icon: 'Layers' },
    { label: 'Semanas', path: '/admin/semanas', icon: 'Calendar' },
    { label: 'Treinos', path: '/admin/treinos', icon: 'Dumbbell' },
    { label: 'WODs', path: '/admin/wods', icon: 'Flame' },
    { label: 'Niveis', path: '/admin/niveis', icon: 'BarChart3' },
    { label: 'Biblioteca', path: '/admin/biblioteca', icon: 'BookOpen' },
    { label: 'Rankings', path: '/admin/rankings', icon: 'Trophy' },
    { label: 'Relatorios', path: '/admin/relatorios', icon: 'FileBarChart' },
    { label: 'Configuracoes', path: '/admin/configuracoes', icon: 'Settings' },
    { label: 'Box', path: '/admin/box', icon: 'Building2' },
    { label: 'Auditoria', path: '/admin/auditoria', icon: 'Activity' },
  ],
  coach: [
    { label: 'Dashboard', path: '/coach/dashboard', icon: 'LayoutDashboard' },
    { label: 'Alunos', path: '/coach/alunos', icon: 'Users' },
    { label: 'Evolucao', path: '/coach/evolucao', icon: 'TrendingUp' },
    { label: 'Resultados', path: '/coach/resultados', icon: 'ClipboardCheck' },
    { label: 'Comentarios', path: '/coach/comentarios', icon: 'MessageSquare' },
    { label: 'Frequencia', path: '/coach/frequencia', icon: 'CalendarCheck' },
    { label: 'Rankings', path: '/coach/rankings', icon: 'Trophy' },
    { label: 'Relatorios', path: '/coach/relatorios', icon: 'FileBarChart' },
  ],
  aluno: [
    { label: 'Dashboard', path: '/aluno/dashboard', icon: 'LayoutDashboard' },
    { label: 'Programacao', path: '/aluno/programacao', icon: 'CalendarDays' },
    { label: 'Treino', path: '/aluno/treino', icon: 'Dumbbell' },
    { label: 'Resultado', path: '/aluno/resultado', icon: 'Target' },
    { label: 'Historico', path: '/aluno/historico', icon: 'History' },
    { label: 'PRs', path: '/aluno/prs', icon: 'Zap' },
    { label: 'Frequencia', path: '/aluno/frequencia', icon: 'CalendarCheck' },
    { label: 'Evolucao', path: '/aluno/evolucao', icon: 'TrendingUp' },
    { label: 'Rankings', path: '/aluno/rankings', icon: 'Trophy' },
    { label: 'Perfil', path: '/aluno/perfil', icon: 'User' },
  ],
} as const
